# Generated by Django 6.0.7 on 2026-07-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_paymentsettings_alter_category_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier_partner',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for order/payment rejection'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_notes',
            field=models.TextField(blank=True, default='', help_text='Admin courier & delivery notes'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_proof_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING_VERIFICATION', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='utr_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='is_qr_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='is_razorpay_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='qr_code_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='upi_id',
            field=models.CharField(default='kuduchee@upi', max_length=100),
        ),
    ]
