# Generated by Django 6.0.7 on 2026-07-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_courier_partner_order_rejection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='AUTUMN / WINTER STUDIO COLLECTION', max_length=255)),
                ('title', models.CharField(default='Opulence Fired in Stoneware.', max_length=255)),
                ('quote', models.TextField(default='Elegance is when the inside is as beautiful as the outside.')),
                ('cta_text', models.CharField(default='Discover Collection', max_length=100)),
                ('cta_link', models.CharField(default='/shop', max_length=255)),
                ('image_url', models.URLField(default='https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=1600&q=85', max_length=500)),
                ('accent_badge', models.CharField(default='Handcrafted Batch 06 · Limited Run', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_text', models.TextField(default='Free shipping on orders above ₹999 · Handcrafted in small batches · Lead-free & 100% vegetarian porcelain')),
                ('brand_quote', models.TextField(default='Elegance is when the inside is as beautiful as the outside.')),
                ('brand_author', models.CharField(default='Kuduchee', max_length=100)),
                ('contact_email', models.CharField(default='anil@kuduchee.in', max_length=100)),
                ('contact_phone', models.CharField(default='9971118219', max_length=50)),
                ('company_legal_name', models.CharField(default='Kaviz Creations Pvt Ltd', max_length=150)),
                ('company_location', models.CharField(default='Ahmedabad, Gujarat', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
