# Generated by Django 6.0.7 on 2026-07-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_herobanner_sitesettings_alter_order_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Only approved reviews are shown publicly on the product page.'),
        ),
    ]
