# Generated by Django 6.0.7 on 2026-07-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_review_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_bank_details',
            field=models.JSONField(blank=True, help_text='Bank details for refund', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_transaction_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCEL_REQUESTED', 'Cancel Requested'), ('CANCELLED', 'Cancelled'), ('REFUND_PROCESSED', 'Refund Processed'), ('REJECTED', 'Rejected')], default='PENDING_VERIFICATION', max_length=30),
        ),
    ]
