# Generated by Django 6.0.7 on 2026-07-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_cancellation_reason_order_refund_bank_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='brand_quote',
            field=models.TextField(default='Serve What You Deserve.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_legal_name',
            field=models.CharField(default='Kaviz Creations Private Limited', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_location',
            field=models.CharField(default='510 A, Sun West Bank, Ashram Road, Ahmedabad, Gujarat 380009', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.CharField(default='anil.panda@kuduchee.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='ticker_text',
            field=models.TextField(default='Free shipping on orders above ₹999 · Designing Experiences Around Every Meal · Lead-free & 100% vegetarian porcelain'),
        ),
    ]
