# Generated by Django 6.0.7 on 2026-08-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_subcategory_and_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.CharField(default='info@kuduchee.in', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='9599652190', max_length=50),
        ),
    ]
